name: first-workflow
on: push

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: Running the single command
        run : echo "Welcome to github"
      - name: version check
        run : cat /etc/os-release
  job2:
    name: job2
    runs-on: ubuntu-latest
    steps:
      - name: hostname checking
        run: hostname -f
      - name: multiple runs
        run: |
            echo: "Hello This is Arun"
            echo: "Welcome to Github Actions"
            sleep: 20 
